name       : hyphen-de
version    : 2007.02.17
release    : 1
source     :
    - http://download.services.openoffice.org/contrib/dictionaries/hyph_de_DE.zip : 731a87fb5ed128341b4178b1dee11819fd5e7392e4ac0526c318d9ab28cf61c9
license    : LGPL-2.0-or-later
component  : office
summary    : German hyphenation rules
description: |
    German hyphenation rules.
rundeps    :
    - hyphen
install    : |
    install -Dm00644 hyph_de_DE.dic $installdir/usr/share/hyphen/hyph_de_DE.dic

    pushd $installdir/usr/share/hyphen/
        de_DE_aliases="de_AT de_BE de_CH de_LI de_LU"
        for lang in ${de_DE_aliases}; do
            ln -s hyph_de_DE.dic hyph_${lang}.dic
        done
    popd
